apiVersion: v2
name: nginx
description: A Helm chart for Kubernetes to deploy Nginx
type: application
version: 1.0.0
appVersion: 1.27.0
maintainers:
  - name: van chin
    email: vlvanchin+work@gmail.com
